name: Deploy to GitHub

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      DISCORD_CI_WEBHOOK:
        required: true

jobs:
  prepare:
    name: Prepare
    uses: bdrelling/ci/.github/workflows/prepare.yml@main

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Build and Push Container
        uses: bdrelling/ci/.github/actions/build-and-push-container@main
        with:
          registry: ghcr.io
          registry_name: ${{ github.actor }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ github.token }}
          image_name: ${{ inputs.image_name }}

  # Send notification to Discord on failure.
  send_notification:
    name: Send Notification
    uses: bdrelling/ci/.github/workflows/send_notification.yml@main
    needs: [deploy]
    if: failure()
    secrets: inherit
