name: Send Notification

on:
  workflow_call:
    secrets:
      DISCORD_CI_WEBHOOK:
        required: true

jobs:
  send_notification:
    name: Send Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_CI_WEBHOOK }}
          title: Tests Failed
          status: Failure
          color: 0xff0000
