name: Swift Test (Linux)

on:
  workflow_call:
    inputs:
      scheme:
        required: true
        type: string
      swift_version:
        required: true
        type: string
      output_directory:
        required: false
        type: string
        default: deploy
      subcommand:
        required: false
        type: string
        default: test

env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  swift_test_linux:
    name: swift test (Ubuntu, Swift ${{ inputs.swift_version }})
    # Available Runners: https://github.com/actions/virtual-environments
    runs-on: ubuntu-latest
    # Available Docker Images: https://hub.docker.com/_/swift/
    container: swift:${{ inputs.swift_version }}-focal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # We need to install curl, since the swift:XX-focal container image doesn't include it.
      - name: Install curl
        run: apt-get update && apt-get install -y curl
      - name: Swift Version Check
        run: swift --version
      - name: Run Tests
        # Download and run our swift_test script. Note that "bash -s --" is explicitly required before arguments.
        # TODO: the --output command here is brittle since it can pass an empty string and break the next argument.
        run: curl -sL https://raw.githubusercontent.com/bdrelling/workflows/main/scripts/swift_test.sh | bash -s -- --scheme ${{ inputs.scheme }} --output ${{ inputs.output_directory }} --subcommand ${{ inputs.subcommand }}
      - name: Upload Step Output
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: Output (Ubuntu, Swift ${{ inputs.swift_version }})
          path: ${{ inputs.output_directory }}
