name: Swift Test

on:
  workflow_call:
    inputs:
      scheme:
        description: 'The scheme within our package to test or build.'
        required: true
        type: string
      subcommand:
        description: 'The subcommand to use. (eg. xcodebuild <subcommand>) Valid options are: test, build'
        required: false
        type: string
        default: test
      platforms:
        description: 'A space-delimited list of platforms to test. Valid options are: iOS, macOS, tvOS, watchOS, visionOS, Linux'
        required: false
        type: string
        default: macOS
      swift-versions:
        description: 'A space-delimited list of Swift version to test. Does not support patch versions (eg. 5.4.1).  Valid options are: 5.7 or greater'
        required: false
        type: string
        default: '5.7 5.8 5.9'
      args:
        description: 'Additional arguments to use. For valid options, run `$ swift <subcommand> --help`.'
        required: false
        type: string
        default: ''
    secrets:
      DISCORD_CI_WEBHOOK:
        required: true
      CODECOV_TOKEN:
        required: false

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # Generate a dynamic matrix to use for testing.
  create_swift_test_matrix:
    name: Create Swift Test Matrix
    runs-on: ubuntu-latest
    steps:
      - name: Create Swift Test Matrix
        id: create_swift_test_matrix
        # As of September 2022, we cannot reference local actions from a reusable workflow.
        uses: bdrelling/ci/.github/actions/create-swift-test-matrix@main
        with:
          platforms: ${{ inputs.platforms }}
          swift-versions: ${{ inputs.swift-versions }}
          subcommand: ${{ inputs.subcommand }}
          debug: true
    outputs:
      test-matrix: ${{ steps.create_swift_test_matrix.outputs.test-matrix }}

  # Run our test script.
  swift_test:
    name: ${{ matrix.inputs.build-method }} ${{ matrix.inputs.subcommand }} (${{ matrix.inputs.platform }}, swift ${{ matrix.inputs.swift-version }})
    runs-on: ${{ matrix.inputs.runner }}
    container: ${{ matrix.inputs.container }}
    needs: [create_swift_test_matrix]
    strategy:
      fail-fast: false
      matrix:
        inputs: ${{ fromJSON(needs.create_swift_test_matrix.outputs.test-matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Tests
        # As of September 2022, we cannot reference local actions from a reusable workflow.
        uses: bdrelling/ci/.github/actions/swift-test@main
        with:
          scheme: ${{ inputs.scheme }}
          platform: ${{ matrix.inputs.platform }}
          build-method: ${{ matrix.inputs.build-method }}
          subcommand: ${{ matrix.inputs.subcommand }}
          swift-version: ${{ matrix.inputs.swift-version }}
          args: ${{ inputs.args }}
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        if: ${{ secrets.CODECOV_TOKEN != '' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          # handle_no_reports_found: false
          # directory: ${{ env.COVERAGE_REPORT_DIRECTORY }}
          verbose: true

  # Send notification to Discord on failure.
  send_notification:
    name: Send Notification
    uses: ./.github/workflows/send_notification.yml
    needs: [swift_test]
    if: failure()
    secrets: inherit
