name: Swift Test (Plugin)

# Tests a package for Swift 5.6+ (plugin support) and greater on all Apple platforms and Linux.

on:
  workflow_call:
    inputs:
      scheme:
        required: true
        type: string
      subcommand:
        required: false
        type: string
        default: test
    secrets:
      DISCORD_CI_WEBHOOK:
        required: true

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
  swift_test_apple:
    uses: ./.github/workflows/swift_test_apple.yml
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: macOS, build_method: xcodebuild }
          - { name: macOS, build_method: swift }
    with:
      scheme: ${{ inputs.scheme }}
      subcommand: ${{ inputs.subcommand }}
      xcode_version: 13.4 # swift 5.6
      platform: ${{ matrix.platform.name }}
      build_method: ${{ matrix.platform.build_method }}
  swift_test_linux:
    uses: ./.github/workflows/swift_test_linux.yml
    needs: [prepare]
    with:
      scheme: ${{ inputs.scheme }}
      subcommand: ${{ inputs.subcommand }}
      swift_version: 5.6
  send_notifications:
    runs-on: ubuntu-latest
    needs: [swift_test_apple, swift_test_linux]
    if: failure()
    steps:
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_CI_WEBHOOK }}
          title: Tests Failed
          status: Failure
          color: 0xff0000
