name: Swift Test

on:
  workflow_call:
    inputs:
      scheme:
        required: true
        type: string
      subcommand:
        required: false
        type: string
        default: test
      platforms:
        required: false
        type: string
        default: macOS
      swift-versions:
        required: false
        type: string
        default: '5.6'

jobs:
  prepare:
    uses: bdrelling/ci/.github/workflows/prepare.yml@main
  # TODO: Add a job here that builds the matrix for the next step, based on minimum_swift_version and platforms
  # Example: https://michaelheap.com/dynamic-matrix-generation-github-actions/
  test-matrix:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: test-matrix
        uses: ./.github/actions/swift-prepare
        with:
          platforms: ${{ inputs.platforms }}
          swift-versions: ${{ inputs.swift-versions }}
          debug: true
    outputs:
      test-matrix: ${{ steps.test-matrix.outputs.test-matrix }}
  swift_test:
    name: ${{ matrix.inputs.build-method }} ${{ inputs.subcommand }} (${{ matrix.inputs.platform }}, swift ${{ matrix.inputs.swift-version }})
    runs-on: ${{ matrix.inputs.runner }}
    needs: [test-matrix]
    strategy:
      fail-fast: false
      matrix:
        inputs: ${{ fromJSON(needs.test-matrix.outputs.test-matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/swift-test
        with:
          scheme: ${{ inputs.scheme }}
          platform: ${{ matrix.inputs.platform }}
          build-method: ${{ matrix.inputs.build-method }}
          subcommand: ${{ inputs.subcommand }}
          swift-version: ${{ matrix.inputs.swift-version }}
  send_notifications:
    runs-on: ubuntu-latest
    needs: [swift_test]
    if: failure()
    steps:
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_CI_WEBHOOK }}
          title: Tests Failed
          status: Failure
          color: 0xff0000
