name: Swift Test (Vapor Package)

# Tests a Vapor package for Swift 5.5+ (for concurrency support) and greater on macOS and Linux.

on:
  workflow_call:
    inputs:
      scheme:
        required: true
        type: string
      subcommand:
        required: false
        type: string
        default: test
    secrets:
      DISCORD_CI_WEBHOOK:
        required: true

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
  swift_test_apple:
    uses: ./.github/workflows/swift_test_apple.yml
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        xcode_version:
          - 13.2 # swift 5.5
          - 13.4 # swift 5.6
    with:
      scheme: ${{ inputs.scheme }}
      subcommand: ${{ inputs.subcommand }}
      xcode_version: ${{ matrix.xcode_version }}
      platform: macOS
      build_method: swift
  swift_test_linux:
    uses: ./.github/workflows/swift_test_linux.yml
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        swift_version: [5.5, 5.6]
    with:
      scheme: ${{ inputs.scheme }}
      subcommand: ${{ inputs.subcommand }}
      swift_version: ${{ matrix.swift_version }}
  send_notifications:
    runs-on: ubuntu-latest
    needs: [swift_test_apple, swift_test_linux]
    if: failure()
    steps:
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_CI_WEBHOOK }}
          title: Tests Failed
          status: Failure
          color: 0xff0000
      # TODO: Troubleshooting
  troubleshooting:
    runs-on: ubuntu-latest
    needs: [swift_test_apple, swift_test_linux]
    if: always()
    steps:
      # - name: machine echo github
      #   env: { CONTENT: '${{ toJSON(github) }}' }
      #   run: 'echo $CONTENT'
      # - name: machine echo env
      #   env: { CONTENT: '${{ toJSON(env) }}' }
      #   run: 'echo $CONTENT'
      # - name: machine echo job
      #   env: { CONTENT: '${{ toJSON(job) }}' }
      #   run: 'echo $CONTENT'
      - name: machine echo jobs
        env: { CONTENT: '${{ toJSON(jobs) }}' }
        run: 'echo $CONTENT'
      # - name: machine echo steps
      #   env: { CONTENT: '${{ toJSON(steps) }}' }
      #   run: 'echo $CONTENT'
      # - name: machine echo runner
      #   env: { CONTENT: '${{ toJSON(runner) }}' }
      #   run: 'echo $CONTENT'
      # - name: machine echo secrets
      #   env: { CONTENT: '${{ toJSON(secrets) }}' }
      #   run: 'echo $CONTENT'
      # - name: machine echo strategy
      #   env: { CONTENT: '${{ toJSON(strategy) }}' }
      #   run: 'echo $CONTENT'
      # - name: machine echo matrix
      #   env: { CONTENT: '${{ toJSON(matrix) }}' }
      #   run: 'echo $CONTENT'
      - name: machine echo needs
        run: echo '${{ toJSON(needs) }}'
      # - name: machine echo inputs
      #   env: { CONTENT: '${{ toJSON(inputs) }}' }
      #   run: 'echo $CONTENT'
